# Generated by Django 3.2.7 on 2021-10-06 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(choices=[('15', '15'), ('30', '30'), ('45', '45'), ('60', '59')], default=30)),
                ('subscription', models.BooleanField(default=True)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_app.webuser')),
                ('websiteInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_app.website')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('WebInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor_app.webdata')),
            ],
        ),
    ]
