# Generated by Django 3.2.7 on 2021-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
